### ISSUE TITLE
update for new koa version?

### ISSUE THREAD

**Issue by ianstormtaylor** [Treri/koa-noop#1]
Hey @Treri, any plans to update this for the newest version of Koa? Would love to use it!

**Comment by ik0r** [comment]
I will do

**Comment by ik0r** [comment]
```js
module.exports = function(_, next){
  return next();
}
```

will be ok?

I use invoke promise here insteadof use `async` and `await`  because some user may not use node 7.6+

**Comment by ianstormtaylor** [comment]
I think that'll work! Thank you!

**Comment by ik0r** [comment]
published version 1.0.1
